fixed 01-inline-styles, added tests, fixed numbers and casing of all exercises
4GeeksAcademy/css-tutorial-exercises-course pull request #138
Opened 2024-03-20 11:10 UTC by josemoracard

…exercises

2024-03-21 12:54 UTC, tommygonzaleza requested changes

2024-03-21 12:54 UTC, tommygonzaleza commented on exercises/01-inline-styles/tests.js
> +const { JSDOM } = require('jsdom');
No estamos usando esta libreria por lo que no va a funcionar

2024-03-21 13:40 UTC, josemoracard commented on exercises/01-inline-styles/tests.js
> +const { JSDOM } = require('jsdom');
done

2024-03-22 19:02 UTC, tommygonzaleza approved these changes

2024-04-09 00:29 UTC, merged